---
  - name: "Preparando o server"
    hosts: localhost
    connection: local

    tasks:

    - name: "Instala Pacotes Iniciais"
      yum:   
        name: "{{ item }}"
        state: present
      loop:
        - bash-completion
        - yum-utils
        - vim
        - bind-utils
        - net-tools
        - telnet
        - wget
        - curl
        - git
        - gcc-c++
        - make
        - automake

    - name: "Configura repo NodeJS"
      shell: "curl -sL https://rpm.nodesource.com/setup_12.x | sudo bash -"

    - name: "Instala NodeJs"
      yum:
        name: nodejs
        state: present
    