---
  - name: "Preparando o server"
    hosts: localhost
    connection: local

    tasks:
     
    - name: "Instala Pacotes Iniciais"
      yum:   
        name: "{{ item }}"
        state: present
      loop:
        - bash-completion
        - yum-utils
        - vim
        - bind-utils
        - net-tools
        - telnet
        - wget
        - curl
        - git
        - gcc-c++
        - make
        - automake
        - nginx
    
    - name: Template Vhost
      template:
        src: vhost.conf.j2
        dest: /etc/nginx/conf.d/vhost.conf
        owner: root
        group: root
        mode: '0644'
  
    - name: "Configura repo NodeJS"
      shell: echo "127.0.0.1   {{ appdomain }}" >> /etc/hosts && echo "::1         {{ appdomain }}" >> /etc/hosts

    - name: "Configura repo NodeJS"
      shell: "curl -sL https://rpm.nodesource.com/setup_12.x | sudo bash -"

    - name: "Instala NodeJs"
      yum:
        name: nodejs
        state: present

    - name: "Cria usuario node"
      user: 
        name: node
        comment: Node App user
        shell: /bin/bash
  
    - name: Clona repo no usuario node
      shell: su - node -c "cd /home/node && git clone https://github.com/adansmashni/desafio.git"
    
    - name: Template Deploy
      template:
        src: deploy.sh.j2
        dest: "{{ appdir }}/deploy.sh"
        owner: node
        group: node
        mode: '0744'

    - name: inicia npm
      shell: su - node -c "cd {{ appdir }} && npm init -y -f"

    - name: instala pm2
      shell: su - node -c "cd {{ appdir }} && npm install pm2 -g"

    - name: instala pm2 modules
      shell: su - node -c "cd {{ appdir }} && while read line; do npm install $line --save; done < requirements.txt"